### ISSUE TITLE
Nodes using generated certificates fail handshake with KEY_USAGE_BIT_INCORRECT 

### ISSUE THREAD

**Issue by yolibernal** [OpenFogStack/FReD#1]
When using the certificates generated with `nase/tls/gen-cert.sh` for FReD nodes and interacting with them using a Python gRPC client, the requests fail with:

```
ssl_transport_security.cc:1455] Handshake failed with fatal error SSL_ERROR_SSL: error:1000012e:SSL routines:OPENSSL_internal:KEY_USAGE_BIT_INCORRECT.
```
The error is possibly raised at the certificate verification step for which I did not find an option to disable it in the Python client.

Currently, the certificates are generated with the extended usages `serverAuth` and `clientAuth`. According to [this](https://superuser.com/questions/738612/openssl-ca-keyusage-extension/1248085#1248085) the `extendedKeyUsages` 

* `serverAuth` requires "digitalSignature, keyEncipherment or keyAgreement"
* `clientAuth` requires "digitalSignature and/or keyAgreement" 

Adding `digitalSignature` to `nase/tls/gen-cert.sh` so

```
keyUsage = keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth, clientAuth
```

looks like this

```
keyUsage = keyEncipherment, dataEncipherment, digitalSignature
extendedKeyUsage = serverAuth, clientAuth
```
resolved the issue for me.

## Example

```py
# Loading certificates
with open("./cert/client.crt", "rb") as f:
    client_crt = f.read()

with open("./cert/client.key", "rb") as f:
    client_key = f.read()

with open("./cert/ca.crt", "rb") as f:
    ca_crt = f.read()

creds = grpc.ssl_channel_credentials(
    certificate_chain=client_crt,
    private_key=client_key,
    root_certificates=ca_crt,
)

host = "172.26.3.1"
port = 9001
target = f"{host}:{port}"
with grpc.secure_channel(target, credentials=creds) as channel:
    stub = client_pb2_grpc.ClientStub(channel)
    response = stub.CreateKeygroup(
        client_pb2.CreateKeygroupRequest(keygroup="somegroup", mutable=True)
    )
    print(response)
```

**Comment by pfandzelter** [comment]
fixed in c458b61d2b770f71b4f9cd942d031520badb85ad. Thanks!
